name: Deploy dbt to Composer

on:
  push:
    branches:
      - main
    paths:
      - 'dbt_airflow_test/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # CRITICAL: These permissions are required for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Replace YOUR_PROJECT_NUMBER and YOUR_PROJECT_ID below!
          workload_identity_provider: 'projects/845747503849/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-actions-composer-deploy@test-and-try-499509.iam.gserviceaccount.com'

      # Step 1: Deploy the Airflow DAG to the /dags folder
      - name: Deploy Airflow DAGs
        run: |
          gcloud storage rsync ./dags gs://dbt_airflow_test_composer/dags --recursive --delete-unmatched-destination-objects

      # Step 2: Deploy the dbt project to the /data folder
      - name: Deploy dbt Project
        run: |
          gcloud storage rsync ./dbt_airflow_test gs://dbt_airflow_test_composer/data/dbt_airflow_test --recursive --delete-unmatched-destination-objects