name: Build and Run dbt on Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "new-map-project-1538399427267"
  GAR_LOCATION: "us-central1"
  REPOSITORY: "dbt-images"
  IMAGE_NAME: "dbt-snowflake"
  JOB_NAME: "dbt-snowflake-production-job"
  WORKFLOW_NAME: "dbt-orchestrator"
  WIF_PROVIDER: "projects/995265336172/locations/global/workloadIdentityPools/github-dbt-pool/providers/github-dbt-provider"
  GCP_SERVICE_ACCOUNT: "github-actions-dbt@new-map-project-1538399427267.iam.gserviceaccount.com"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # for secrets in github
    environment: prod

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      
      # 2. Log in directly to Artifact Registry using the generated token
      - name: Log in to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # 3. Build and Tag the Production Docker Image using the subfolder context
      - name: Build and Tag Image
        run: |
          IMAGE_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG ./dbt_airflow_test

      # 4. Push the Image to Google Cloud Artifact Registry
      - name: Push Image to Registry
        run: |
          docker push ${{ env.IMAGE_TAG }}

      # 5. Create or Update the Cloud Run Job (Points Job to the New Image!)
      - name: Deploy Cloud Run Job
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          job: ${{ env.JOB_NAME }}
          image: ${{ env.IMAGE_TAG }}
          region: ${{ env.GAR_LOCATION }}
          flags: --max-retries=0
          env_vars: |-
            SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
            SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}
            SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}
            SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}
            SNOWFLAKE_SCHEMA=${{ secrets.SNOWFLAKE_SCHEMA }}

      # 6. Deploy the latest Workflows YAML to Google Cloud
      - name: Deploy Cloud Workflow
        run: |
          gcloud workflows deploy ${{ env.WORKFLOW_NAME }} \
            --source=config/workflow.yaml \
            --location=${{ env.GAR_LOCATION }}

      # 7. Trigger the Workflow to Run Immediately
      # Using 'run' instead of 'execute' makes GitHub wait synchronously for the Workflow to succeed/fail
      - name: Execute Cloud Workflow
        run: |
          gcloud workflows run ${{ env.WORKFLOW_NAME }} \
            --location=${{ env.GAR_LOCATION }}